imports:
    - { resource: manager.yml }
    - { resource: twig.yml }

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
