<?php

namespace BlogBundle\Repository;

/**
 * ThemeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeUserRepository extends \Doctrine\ORM\EntityRepository
{
}
