<?php

namespace BlogBundle\Repository;

/**
 * ThemeOfficielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeOfficielRepository extends \Doctrine\ORM\EntityRepository
{
}
