<?php

namespace BlogBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	/*public function userRoleTous() {  	
	
	$queryBuilder = $this->createQueryBuilder('u');
        $this->createQueryBuilder('u')->join('u.roles', 'r')->addSelect('r')->where('r.id = :id');

        return $queryBuilder->getQuery()->getResult();
    }*/

}
