<?php

namespace BlogBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	/*public function afficherTous() 
	{
        return $this->getEntityManager()
                        ->createQuery('SELECT role FROM BlogBundle:Role ORDER BY id ASC')->getResult();
    }*/ 	
}
